### ISSUE TITLE
Hint System

### ISSUE THREAD

**Issue by Jonanory** [Jonanory/ReputationsGame#10]
Make a hint system, which determines the difficulty:
- [ ] V. Easy: Logical deductions are told to the player at appropriate times (#62)
- [ ] Easy: Innocence of character makes reputations work in favour of the player (#63)
- [ ] Medium: Psychology hints told to player at appropriate times (#61)
- [ ] Hard: Sidekick ramblings hold subtle hints at what to do (#60)
- [x] V. Hard: No hints at all
